# ============================================ Prepare Environment ===================================================
Sys.setenv(LANGUAGE = "en")
options(stringsAsFactors = FALSE)
rm(list=ls());gc()
setwd("workspace")
getwd()
library(qs)
library(tibble)
library(DESeq2)
library(dplyr)
library(Seurat)
library(ggpubr)
library(cowplot)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(cowplot)
library(stringr)
library(ggsci)
library(SCOP)
library(pheatmap)
library(ggrepel)
library(gplots)
set.seed(1234)
list.files()
dir.create("./07.GE/")


# ============================================ Load Data ===================================================
seurat_obj <- qread("seurat_obj.qs")
